In [0]:
import pandas as pd
# count, sum, min, max Operations on DataFrame
# DataFrame from Dictionary 

df = pd.DataFrame({'Name':['amit', 'sumit', 'riya', 'dev', 'kavita'],
                    'Age': [20, 21, 33, 23, 16],
                    'Address': ['bhopal', 'patna', 'delhi', 'bangalore', 'raipur'],
                    'kg': [56, 50, 45, 55, 66]})
df

     Name  Age    Address  kg
0    amit   20     bhopal  56
1   sumit   21      patna  50
2    riya   33      delhi  45
3     dev   23  bangalore  55
4  kavita   16     raipur  66

In [0]:
#1. count 
df[['Age']].count()

Age    5
dtype: int64

In [0]:
#2. sum
df[['Age']].sum()

Age    113
dtype: int64

In [0]:
#3. mean
df[['Age']].mean()

Age    22.6
dtype: float64

In [0]:
#4. average
df[['Age']].sum()/df[['Age']].count()

Age    22.6
dtype: float64

In [0]:
#5. Min
df[['Age']].min()

Age    16
dtype: int64

In [0]:
#6. Max
df[['Age']].max()

Age    33
dtype: int64

In [0]:
#7. Min Index
df[['Age']].idxmin()

Age    4
dtype: int64

In [0]:
#8. Max Index
df[['Age']].idxmax()

Age    2
dtype: int64

In [0]:
#9. Summary of data
df[['Age']].describe()

             Age
count   5.000000
mean   22.600000
std     6.348228
min    16.000000
25%    20.000000
50%    21.000000
75%    23.000000
max    33.000000

In [0]:
df[['Age','kg']].describe()

             Age         kg
count   5.000000   5.000000
mean   22.600000  54.400000
std     6.348228   7.829432
min    16.000000  45.000000
25%    20.000000  50.000000
50%    21.000000  55.000000
75%    23.000000  56.000000
max    33.000000  66.000000

In [0]:
df.describe()

             Age         kg
count   5.000000   5.000000
mean   22.600000  54.400000
std     6.348228   7.829432
min    16.000000  45.000000
25%    20.000000  50.000000
50%    21.000000  55.000000
75%    23.000000  56.000000
max    33.000000  66.000000